name: Upload File to Backblaze B2 using rClone

on:
  repository_dispatch:
    types: ['download']
jobs:
  upload_to_b2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install rClone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    - name: Configure rClone for B2
      run: |
        mkdir -p ~/.config/rclone/
        echo "[b2-backup]" > ~/.config/rclone/rclone.conf
        echo "type = b2" >> ~/.config/rclone/rclone.conf
        echo "account = ${{ secrets.B2_ACCOUNT_ID }}" >> ~/.config/rclone/rclone.conf
        echo "key = ${{ secrets.B2_APPICATION_KEY }}" >> ~/.config/rclone/rclone.conf

    - name: Upload File to B2
      run: |
        rclone copy text_passage.txt b2-backup:${{ secrets.B2_BUCKET_NAME }}
      env:
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
