name: Upload File to Backblaze B2 using rClone

on:
  repository_dispatch:
    types: ['download']

jobs:
  upload_to_b2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install rClone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    - name: Configure rClone for B2
      run: |
        rclone config create b2-backup b2 \
          account=$B2_ACCOUNT_ID \
          key=$B2_APPLICATION_KEY \
          --non-interactive
      env:
        B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPICATION_KEY }}

    - name: Upload File to B2
      run: |
        rclone copy path/to/your/file.txt b2-backup:${{ secrets.B2_BUCKET_NAME }} --b2-chunk-size 96M

