name: Upload File to Backblaze B2

on:
  repository_dispatch:
     types: ['download']

jobs:
  upload_to_b2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install B2 CLI
      run: |
        pip install b2

    - name: Get B2 Auth Token
      id: b2_auth
      run: |
        B2_ACCOUNT_ID=${{ secrets.B2_ACCOUNT_ID }}
        B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }}
        auth_result=$(b2 authorize-account $B2_ACCOUNT_ID $B2_APPLICATION_KEY)
        echo "name=auth_token::$(echo $auth_result | jq -r '.authorizationToken')" >> $GITHUB_OUTPUTS
        echo "name=api_url::$(echo $auth_result | jq -r '.apiUrl')" >> $GITHUB_OUTPUTS
        echo "name=download_url::$(echo $auth_result | jq -r '.downloadUrl')" >> $GITHUB_OUTPUTS
        echo "name=account_id::$(echo $auth_result | jq -r '.accountId')" >> $GITHUB_OUTPUTS

    - name: Get Upload URL
      id: b2_upload_url
      run: |
        BUCKET_NAME=${{ secrets.B2_BUCKET_NAME }}
        UPLOAD_URL_RESULT=$(b2 get-upload-url $BUCKET_NAME)
        echo "name=upload_url::$(echo $UPLOAD_URL_RESULT | jq -r '.uploadUrl')" >> $GITHUB_OUTPUTS
        echo "name=authorization_token::$(echo $UPLOAD_URL_RESULT | jq -r '.authorizationToken')" >> $GITHUB_OUTPUTS

    - name: Upload File to B2
      run: |
        FILE_TO_UPLOAD="Dev21Maker/MAGitAPI/text_passage.txt"
        UPLOAD_URL=${{ steps.b2_upload_url.outputs.upload_url }}
        AUTHORIZATION_TOKEN=${{ steps.b2_upload_url.outputs.authorization_token }}
        curl -H "Authorization: $AUTHORIZATION_TOKEN" \
             -F "file=@$FILE_TO_UPLOAD" \
             -F "bucket=${{ secrets.B2_BUCKET_NAME }}" \
             "$UPLOAD_URL"
