name: Scrape latest schemas

on:
  workflow_dispatch:
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: GitHub
      run: npx @puppeteer/browsers install chrome@116.0.5793.0
