name: Puppeteer Automation 2

on: 
  repository_dispatch:
    types: ['figma']

jobs:
  run-api-puppeteer:
    runs-on: ubuntu-latest
    outputs: 
      status: ${{ steps.result.outputs.status }}
    steps:
      - name: Checkut repository
        uses: actions/checkout@v2
      
      - name: Predefine failure
        run: |
          echo "status=failure" >> $GITHUB_ENV

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies  
        run: |
          npm install puppeteer
          npm install puppeteer-extra
          npm install puppeteer-extra-plugin-stealth

      - name: Run Puppeteer script
        run: node figma.js

      - name: Success
        run: |
           echo "status=success" >> $GITHUB_ENV
      - name: Result
        if: always()
        run: |
          echo "status=$status" >> $GITHUB_OUTPUTS
  display:
    needs: run-api-puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: show_result
        run: echo "${{ needs.run-api-puppeteer.outputs.status }}"
  notify:
    needs: run-api-puppeteer
    uses: Dev21Maker/MAGitAPI/.github/workflows/main6.yml@main
    with:
      build_status: ${{ needs.run-api-puppeteer.outputs.status }}
    secrets: inherit         
