name: API TRIGGER
env:
  REPO_OWNER: Dev21Maker
  REPO_NAME: MAGitAPI
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on: 
  repository_dispatch:
    types: ['basic']


jobs:
  api-job-puppeteer:
    runs-on: ubuntu-latest
    env:
     PUPPETEER_CACHE_DIR: ~/.cache/puppeteer
     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install 

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
      - name: Cache Puppeteer browser
        id: cache-puppeteer
        uses: actions/cache@v3  # Use the cache action
        with:
          path: ${{ env.PUPPETEER_CACHE_DIR }}  # Specify the cache directory path
          key: puppeteer-${{ runner.os }}-${{ hashFiles('package-lock.json') }}  # Define a unique cache key
          restore-keys: |
            puppeteer-${{ runner.os }}-  # Allow partial key matching for restoring cache

      - name: Install Puppeteer browser
        run: npm i @puppeteer/browsers@1.7.1 # Install the Puppeteer browser
        env:
          PUPPETEER_CACHE_DIR: ${{ env.PUPPETEER_CACHE_DIR }}  # Use the cache directory path

      - name: Add execute permissions to Chrome binary
        run: chmod +x ./chrome/linux-116.0.5793.0/chrome-linux/chrome

      - name: Run puppeteer script Basic
        run: node app.js
      
      - name: Store file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: script-output
          path: screenshot.png
        
        
    
