name: API TRIGGER

on: 
  repository_dispatch:
    types: ['uizard']
    inputs:
      URL: 
        description: 'Figma url'
        required: true
        default: 'none'

jobs:
  api-job-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install puppeteer
          npm install puppeteer-extra
          npm install puppeteer-extra-plugin-stealth


      - name: Run puppeteer script Uizard
        run: node uizard.js
        env: 
          UIZARD_PASSWORD: ${{ secrets.UIZARD_PASSWORD }}
          LOGIN: ${{ secrets.LOGIN }}
          URL: ${{ github.event.inputs.URL }}
          
      - name: Store file
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: script-output
           path: screenshot.png
        
        
        
    
