name: Puppeteer Automation 2

on: 
  repository_dispatch:
    types: ['figma']

jobs:
  run-api-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkut repository
        uses: actions/checkout@v2

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies  
        run: |
          npm install puppeteer
          npm install puppeteer-extra
          npm install puppeteer-extra-plugin-stealth


      - name: Run Puppeteer script
        run: node figma.js

  notify:
    needs: run-api-puppeteer
    runs-on: ubuntu-latest
    if: always()
  
    steps:
      - name: Call Reusable Workflow
        uses: ./.github/workflows/main6.yml
        with:
          build_status: ${{ needs.build.outputs.status }}    
  
