name: Puppeteer Automation 2

on: 
  repository_dispatch:
    types: ['figma']

jobs:
  run-api-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkut repository
        uses: actions/checkout@v2
      
      - name: Predefine failure
        run: |
          echo "::set-output name=status::failure"

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies  
        run: |
          npm install puppeteer
          npm install puppeteer-extra
          npm install puppeteer-extra-plugin-stealth

      - name: Run Puppeteer script
        run: node figma.js

      - name: Success
        run: |
           echo "::set-output name=status::success"
  notify:
    needs: run-api-puppeteer
    uses: Dev21Maker/MAGitAPI/.github/workflows/main6.yml@main
    with:
      build_status: ${{ needs.run-api-puppeteer.outputs.status }}
    secrets: inherit         
